# Generated by Django 5.0.3 on 2024-05-05 15:58

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_Vietnamese', models.CharField(max_length=50, unique=True)),
                ('title_English', models.CharField(max_length=50)),
                ('describe', models.TextField()),
                ('duration', models.CharField(max_length=20)),
                ('count_episode', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='images')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0)),
                ('actor', models.ManyToManyField(blank=True, null=True, related_name='movie', to='apimovie.actor')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='apimovie.countrymovie')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='apimovie.director')),
                ('genres', models.ManyToManyField(to='apimovie.genremovie')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='apimovie.movietype')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='apimovie.subtitle')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='apimovie.yearmovie')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_episode', models.IntegerField(blank=True, default=1)),
                ('video_file', models.FileField(upload_to='videos')),
                ('video_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='episodes', to='apimovie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_watched', models.FloatField(default=0, help_text='Thời lượng xem của người dùng cho tập phim (đơn vị: giây)', null=True)),
                ('watched_at', models.DateField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='apimovie.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='apimovie.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.customuser')),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.customuser')),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
    ]
