# Generated by Django 5.0.3 on 2024-05-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='apimovie.movie'),
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.customuser')),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
    ]
