# Generated by Django 5.0.3 on 2024-05-07 17:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0002_alter_episode_movie_watchlater'),
    ]

    operations = [
        
    ]
