# Generated by Django 5.0.3 on 2024-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0003_episode_type'),
    ]

    operations = [
        
    ]
