# Generated by Django 5.0.3 on 2024-05-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0004_alter_episode_id'),
    ]

    operations = [
    ]
