# Generated by Django 5.0.3 on 2024-05-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0005_remove_episode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Customtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimovie.customuser')),
            ],
        ),
    ]
