# Generated by Django 5.0.3 on 2024-05-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0006_alter_episode_id_customtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecomment',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='WatchLater',
        ),
    ]
