# Generated by Django 5.0.3 on 2024-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimovie', '0007_alter_moviecomment_unique_together_delete_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
